version: '3'

services:
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_gateway
    networks:
      - app_network
    deploy:
      replicas: 1

  api_gateway:
    image: api_gateway:latest
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - home_page
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  home_page:
    image: home_page:latest
    networks:
      - app_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  restaurant_service:
    image: restaurant_service:latest
    networks:
      - app_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  order_service:
    image: order_service:latest
    networks:
      - app_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  app_network:
    external: true